### ISSUE TITLE
Fork Notification

### ISSUE THREAD

**Issue by ryantheleach** [OKTW-Network/Galaxy-lobby-resourcepack#1]
Hey Guys!

Just a heads up that I've forked your project, plan on playing around with Inventory GUI's a bit, and it's a lot harder then it looks!

Noticed you had done some of the legwork of trial and error already, and I was struggling to make even the most basic buttons.

Thankyou for releasing under an open source license, I'll continue to do the same for direct modifications to your pack and you have permission to take anything from that repository that I commit for your own, without attribution since you helped me out so much, wouldn't want to make your licensing any more complicated then it already is.

Due to the language barrier though, I probably won't be keeping it in sync with your branch, unless I happen to see something super cool.

I'm also not trying to steal your server concept, you will notice that I'm trying to strip anything Galaxy Specific away from the resource pack, that isn't to remove attribution, but to respect that you have a unique server that you won't want copied too closely, regardless of license.

Hopefully I will come up with something cool that you guys will want as well. 

Much ❤️. 

Ryan

**Comment by mmis1000** [comment]
It's OK to do anything on it if you comply with the MIT license.
You are free to redistribute/modify it if the contributor names and LICENSE are not striped.
We do know what MIT license means, so we choose it to contribute our works to the minecraft community.

Regards.

Mmis1000

**Comment by ryantheleach** [comment]
Sure! I didn't want to imply you didn't. Was just trying to be friendly. :-)
